sirius:
  static_tf2_broadcaster:
    ros__parameters:
      parent_frame: "base_footprint"
      child_frame: "velodyne"
      translation_x: 0.0
      translation_y: 0.0
      translation_z: 1.0
      rotation_x: 0.0
      rotation_y: 0.0
      rotation_z: 0.0